import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Design system tokens
        "surface-container-low": "#eff4ff",
        "surface-dim": "#cbdbf5",
        "error": "#ba1a1a",
        "primary": "#000000",
        "secondary-fixed-dim": "#b4c5ff",
        "on-tertiary-container": "#c76c00",
        "tertiary": "#000000",
        "on-primary-fixed": "#131b2e",
        "on-tertiary": "#ffffff",
        "surface": "#f8f9ff",
        "on-surface-variant": "#45464d",
        "secondary-container": "#316bf3",
        "tertiary-container": "#2f1500",
        "surface-variant": "#d3e4fe",
        "outline-variant": "#c6c6cd",
        "on-secondary-fixed-variant": "#003ea8",
        "on-primary-fixed-variant": "#3f465c",
        "background": "#f8f9ff",
        "on-primary-container": "#7c839b",
        "surface-container-highest": "#d3e4fe",
        "secondary-fixed": "#dbe1ff",
        "inverse-primary": "#bec6e0",
        "on-background": "#0b1c30",
        "on-secondary": "#ffffff",
        "outline": "#76777d",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#213145",
        "tertiary-fixed": "#ffdcc3",
        "inverse-on-surface": "#eaf1ff",
        "primary-fixed-dim": "#bec6e0",
        "primary-container": "#131b2e",
        "on-tertiary-fixed": "#2f1500",
        "on-tertiary-fixed-variant": "#6e3900",
        "secondary": "#0051d5",
        "surface-tint": "#565e74",
        "on-secondary-fixed": "#00174b",
        "surface-container-high": "#dce9ff",
        "surface-bright": "#f8f9ff",
        "primary-fixed": "#dae2fd",
        "on-secondary-container": "#fefcff",
        "surface-container": "#e5eeff",
        "on-error-container": "#93000a",
        "on-surface": "#0b1c30",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#ffb77d",
        "alert-amber": "#d97706",
        "alert-amber-100": "#fef3c7",
        "justice-blue": "#0051d5",
        "justice-blue-100": "#dbe1ff",
        "slate-50": "#f8fafc",
        "slate-100": "#f1f5f9",
        "slate-200": "#e2e8f0",
        "slate-300": "#cbd5e1",
        "slate-500": "#64748b",
        "slate-600": "#475569",
        "slate-900": "#0f172a",
        "deep-navy": "#0b1c30",

        // Standard Tailwind colors used by page components
        "white": "#ffffff",
        "neutral": {
          "50":  "#f8fafc",
          "100": "#f1f5f9",
          "200": "#e2e8f0",
          "300": "#cbd5e1",
          "400": "#94a3b8",
          "500": "#64748b",
          "600": "#475569",
          "700": "#334155",
          "800": "#1e293b",
          "900": "#0f172a",
        },
        "blue": {
          "50":  "#eff6ff",
          "100": "#dbeafe",
          "200": "#bfdbfe",
          "600": "#2563eb",
          "700": "#1d4ed8",
        },
        "green": {
          "50":  "#f0fdf4",
          "100": "#dcfce7",
          "600": "#16a34a",
          "700": "#15803d",
        },
        "purple": {
          "50":  "#faf5ff",
          "100": "#f3e8ff",
          "600": "#9333ea",
          "700": "#7e22ce",
        },
        "orange": {
          "50":  "#fff7ed",
          "100": "#ffedd5",
          "600": "#ea580c",
        },
        "red": {
          "50":  "#fef2f2",
          "100": "#fee2e2",
          "500": "#ef4444",
          "600": "#dc2626",
          "700": "#b91c1c",
        },
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.125rem",
        lg: "0.375rem",
        xl: "0.5rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "40px",
        gutter: "16px",
        "container-max": "1440px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "title-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "label-code": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
export default config;
