-- ============================================================================
-- CUSTODYCORE — Seed Data
-- Auto-generated by 02_seed_generator.py
-- Generated: 2026-05-28T00:30:52.691658
-- ============================================================================

BEGIN;

-- Courts (5)
INSERT INTO courts (court_name, address, contact_phone) VALUES ('Central District Court', '100 Main Street, Capital City', '+1-555-0101');
INSERT INTO courts (court_name, address, contact_phone) VALUES ('North District Court', '200 Oak Avenue, Northville', '+1-555-0102');
INSERT INTO courts (court_name, address, contact_phone) VALUES ('South District Court', '300 Pine Road, Southtown', '+1-555-0103');
INSERT INTO courts (court_name, address, contact_phone) VALUES ('East District Court', '400 Elm Boulevard, Eastside', '+1-555-0104');
INSERT INTO courts (court_name, address, contact_phone) VALUES ('West District Court', '500 Maple Drive, Westpark', '+1-555-0105');

-- Storage Locations (10)
INSERT INTO storage_locations (room, locker, refrigerator, vault, climate_notes, access_level) VALUES ('Room 101', 'Locker A1', NULL, NULL, 'Standard evidence locker', 'restricted');
INSERT INTO storage_locations (room, locker, refrigerator, vault, climate_notes, access_level) VALUES ('Room 101', 'Locker A2', NULL, NULL, 'Standard evidence locker', 'restricted');
INSERT INTO storage_locations (room, locker, refrigerator, vault, climate_notes, access_level) VALUES ('Room 102', NULL, 'Refrigerator B1', NULL, 'Biological evidence — 4C', 'restricted');
INSERT INTO storage_locations (room, locker, refrigerator, vault, climate_notes, access_level) VALUES ('Room 103', 'Locker C1', NULL, 'Vault D1', 'Firearms and currency vault — 24hr monitoring', 'high');
INSERT INTO storage_locations (room, locker, refrigerator, vault, climate_notes, access_level) VALUES ('Room 104', NULL, NULL, NULL, 'Digital evidence processing — anti-static', 'restricted');
INSERT INTO storage_locations (room, locker, refrigerator, vault, climate_notes, access_level) VALUES ('Room 105', 'Locker E1', 'Refrigerator B2', NULL, 'Narcotics — double-locked', 'high');
INSERT INTO storage_locations (room, locker, refrigerator, vault, climate_notes, access_level) VALUES ('Room 201', 'Locker F1', NULL, NULL, 'Long-term storage — climate controlled', 'restricted');
INSERT INTO storage_locations (room, locker, refrigerator, vault, climate_notes, access_level) VALUES ('Crime Lab DNA', NULL, 'Refrigerator B3', NULL, 'DNA lab refrigerator — CofC log required', 'high');
INSERT INTO storage_locations (room, locker, refrigerator, vault, climate_notes, access_level) VALUES ('Crime Lab Tox', NULL, 'Refrigerator B4', NULL, 'Toxicology samples — secure', 'high');
INSERT INTO storage_locations (room, locker, refrigerator, vault, climate_notes, access_level) VALUES ('Courtroom 1', 'Court Locker 1', NULL, NULL, 'Temporary holding during court', 'restricted');

-- Personnel (15)
INSERT INTO personnel (name, badge_number, department, unit, contact, role) VALUES ('Detective Sarah Chen', 'OFC-001', 'Detective Bureau', 'Homicide', 'sarah.chen@pd.gov', 'officer');
INSERT INTO personnel (name, badge_number, department, unit, contact, role) VALUES ('Detective Marcus Johnson', 'OFC-002', 'Detective Bureau', 'Narcotics', 'marcus.johnson@pd.gov', 'officer');
INSERT INTO personnel (name, badge_number, department, unit, contact, role) VALUES ('Officer David Ramirez', 'OFC-003', 'Patrol Division', 'Street Crime', 'david.ramirez@pd.gov', 'officer');
INSERT INTO personnel (name, badge_number, department, unit, contact, role) VALUES ('Detective Emily Watson', 'OFC-004', 'Detective Bureau', 'Digital Forensics', 'emily.watson@pd.gov', 'officer');
INSERT INTO personnel (name, badge_number, department, unit, contact, role) VALUES ('Sergeant James O''Brien', 'OFC-005', 'Detective Bureau', 'Homicide', 'james.obrien@pd.gov', 'officer');
INSERT INTO personnel (name, badge_number, department, unit, contact, role) VALUES ('Dr. Lisa Park', 'LAB-001', 'Crime Lab', 'DNA Analysis', 'lisa.park@lab.gov', 'lab_technician');
INSERT INTO personnel (name, badge_number, department, unit, contact, role) VALUES ('Technician Robert Kim', 'LAB-002', 'Crime Lab', 'Digital Forensics', 'robert.kim@lab.gov', 'lab_technician');
INSERT INTO personnel (name, badge_number, department, unit, contact, role) VALUES ('Analyst Maria Garcia', 'LAB-003', 'Crime Lab', 'Toxicology', 'maria.garcia@lab.gov', 'lab_technician');
INSERT INTO personnel (name, badge_number, department, unit, contact, role) VALUES ('ADA Thomas Mitchell', 'PRO-001', 'Prosecution Office', 'Major Crimes', 'thomas.mitchell@da.gov', 'prosecutor');
INSERT INTO personnel (name, badge_number, department, unit, contact, role) VALUES ('ADA Rachel Nguyen', 'PRO-002', 'Prosecution Office', 'Narcotics Unit', 'rachel.nguyen@da.gov', 'prosecutor');
INSERT INTO personnel (name, badge_number, department, unit, contact, role) VALUES ('ADA Kevin Brown', 'PRO-003', 'Prosecution Office', 'General Crimes', 'kevin.brown@da.gov', 'prosecutor');
INSERT INTO personnel (name, badge_number, department, unit, contact, role) VALUES ('Attorney Michael Torres', 'DEF-001', 'Public Defender''s Office', 'Homicide Defense', 'michael.torres@pd.defense.gov', 'defense_attorney');
INSERT INTO personnel (name, badge_number, department, unit, contact, role) VALUES ('Attorney Jennifer Foster', 'DEF-002', 'Public Defender''s Office', 'General Defense', 'jennifer.foster@pd.defense.gov', 'defense_attorney');
INSERT INTO personnel (name, badge_number, department, unit, contact, role) VALUES ('Attorney Christopher Lee', 'DEF-003', 'Private Defense', 'White Collar', 'chris.lee@defense-law.com', 'defense_attorney');
INSERT INTO personnel (name, badge_number, department, unit, contact, role) VALUES ('Clerk Amanda White', 'CLK-001', 'Court Administration', 'Records', 'amanda.white@courts.gov', 'court_clerk');

-- Cases (8)
INSERT INTO cases (case_number, case_priority, title, description, status, prosecutor_id, defense_id, court_id, hearing_date, opened_date, closed_date)
VALUES ('2026-CR-001', 'critical', 'State v. John Doe', 'Home invasion and aggravated assault', 'closed', 9, 12, 1, '2026-03-15', '2026-01-20', '2026-04-30');
INSERT INTO cases (case_number, case_priority, title, description, status, prosecutor_id, defense_id, court_id, hearing_date, opened_date, closed_date)
VALUES ('2026-CR-002', 'major', 'State v. Jane Smith', 'Drug trafficking — large quantity narcotics', 'closed', 10, 13, 2, '2026-04-10', '2026-02-01', '2026-04-09');
INSERT INTO cases (case_number, case_priority, title, description, status, prosecutor_id, defense_id, court_id, hearing_date, opened_date, closed_date)
VALUES ('2026-CR-003', 'major', 'State v. Robert Wilson', 'Armed robbery of convenience store', 'closed', 9, 14, 3, '2026-05-01', '2026-02-15', '2026-04-17');
INSERT INTO cases (case_number, case_priority, title, description, status, prosecutor_id, defense_id, court_id, hearing_date, opened_date, closed_date)
VALUES ('2026-CR-004', 'critical', 'State v. Angela Martinez', 'Homicide — first degree murder', 'active', 9, 12, 1, '2026-06-20', '2026-03-01', NULL);
INSERT INTO cases (case_number, case_priority, title, description, status, prosecutor_id, defense_id, court_id, hearing_date, opened_date, closed_date)
VALUES ('2026-CR-005', 'major', 'State v. Derek Brown', 'Digital fraud and identity theft ring', 'active', 11, 14, 4, '2026-07-15', '2026-03-10', NULL);
INSERT INTO cases (case_number, case_priority, title, description, status, prosecutor_id, defense_id, court_id, hearing_date, opened_date, closed_date)
VALUES ('2026-CR-006', 'critical', 'State v. Patricia Davis', 'Officer-involved shooting investigation', 'active', 9, 12, 1, '2026-06-01', '2026-04-01', NULL);
INSERT INTO cases (case_number, case_priority, title, description, status, prosecutor_id, defense_id, court_id, hearing_date, opened_date, closed_date)
VALUES ('2026-CR-007', 'minor', 'State v. Kevin Miller', 'Petty theft from retail establishment', 'open', 11, 13, 5, NULL, '2026-05-01', NULL);
INSERT INTO cases (case_number, case_priority, title, description, status, prosecutor_id, defense_id, court_id, hearing_date, opened_date, closed_date)
VALUES ('2026-CR-008', 'major', 'State v. Laura Wilson', 'Burglary and criminal trespass', 'open', 10, 13, 2, NULL, '2026-05-10', NULL);

-- Evidence Items (25)
INSERT INTO evidence_items (asset_tag, description, case_id, evidence_type_id, collected_date, crime_scene_location, current_status, disposal_date, collected_by)
VALUES ('TAG-001001', '9mm handgun — Smith & Wesson, serial SW94827', 1, 6, '2026-01-20T19:15:00', 'Crime scene — 2026-CR-001', 'disposed', '2026-04-30', 1);
INSERT INTO evidence_items (asset_tag, description, case_id, evidence_type_id, collected_date, crime_scene_location, current_status, disposal_date, collected_by)
VALUES ('TAG-001002', 'Blood sample from crime scene — living room floor', 1, 2, '2026-01-20T16:08:00', 'Crime scene — 2026-CR-001', 'disposed', '2026-04-30', 1);
INSERT INTO evidence_items (asset_tag, description, case_id, evidence_type_id, collected_date, crime_scene_location, current_status, disposal_date, collected_by)
VALUES ('TAG-001003', 'Fingerprint lift — door frame, front entrance', 1, 2, '2026-01-20T08:43:00', 'Crime scene — 2026-CR-001', 'disposed', '2026-04-30', 1);
INSERT INTO evidence_items (asset_tag, description, case_id, evidence_type_id, collected_date, crime_scene_location, current_status, disposal_date, collected_by)
VALUES ('TAG-001004', 'Surveillance footage — neighbor security camera', 1, 3, '2026-01-21T12:05:00', 'Crime scene — 2026-CR-001', 'disposed', '2026-04-30', 4);
INSERT INTO evidence_items (asset_tag, description, case_id, evidence_type_id, collected_date, crime_scene_location, current_status, disposal_date, collected_by)
VALUES ('TAG-002001', 'Cocaine hydrochloride — 500g vacuum-sealed brick', 2, 8, '2026-02-02T15:27:00', 'Crime scene — 2026-CR-002', 'disposed', '2026-04-09', 2);
INSERT INTO evidence_items (asset_tag, description, case_id, evidence_type_id, collected_date, crime_scene_location, current_status, disposal_date, collected_by)
VALUES ('TAG-002002', 'Digital scale — Ohaus brand, residue present', 2, 1, '2026-02-01T04:01:00', 'Crime scene — 2026-CR-002', 'disposed', '2026-04-09', 2);
INSERT INTO evidence_items (asset_tag, description, case_id, evidence_type_id, collected_date, crime_scene_location, current_status, disposal_date, collected_by)
VALUES ('TAG-002003', 'Plastic baggies — 200-count, unused', 2, 5, '2026-02-01T07:13:00', 'Crime scene — 2026-CR-002', 'disposed', '2026-04-09', 2);
INSERT INTO evidence_items (asset_tag, description, case_id, evidence_type_id, collected_date, crime_scene_location, current_status, disposal_date, collected_by)
VALUES ('TAG-002004', 'Cellphone — iPhone 15, seizure from suspect', 2, 3, '2026-02-01T16:32:00', 'Crime scene — 2026-CR-002', 'disposed', '2026-04-09', 2);
INSERT INTO evidence_items (asset_tag, description, case_id, evidence_type_id, collected_date, crime_scene_location, current_status, disposal_date, collected_by)
VALUES ('TAG-003001', 'Shotgun — Remington 870, serial RM45123', 3, 6, '2026-02-16T16:01:00', 'Crime scene — 2026-CR-003', 'disposed', '2026-04-17', 1);
INSERT INTO evidence_items (asset_tag, description, case_id, evidence_type_id, collected_date, crime_scene_location, current_status, disposal_date, collected_by)
VALUES ('TAG-003002', 'Cash register receipt — timestamp 22:47', 3, 5, '2026-02-16T13:12:00', 'Crime scene — 2026-CR-003', 'disposed', '2026-04-17', 1);
INSERT INTO evidence_items (asset_tag, description, case_id, evidence_type_id, collected_date, crime_scene_location, current_status, disposal_date, collected_by)
VALUES ('TAG-003003', 'Fingerprint lift — counter surface', 3, 2, '2026-02-16T23:41:00', 'Crime scene — 2026-CR-003', 'disposed', '2026-04-17', 1);
INSERT INTO evidence_items (asset_tag, description, case_id, evidence_type_id, collected_date, crime_scene_location, current_status, disposal_date, collected_by)
VALUES ('TAG-003004', 'Surveillance footage — store CCTV hard drive', 3, 3, '2026-02-16T22:34:00', 'Crime scene — 2026-CR-003', 'disposed', '2026-04-17', 4);
INSERT INTO evidence_items (asset_tag, description, case_id, evidence_type_id, collected_date, crime_scene_location, current_status, disposal_date, collected_by)
VALUES ('TAG-004001', 'Knife — kitchen knife, bloodstains present', 4, 1, '2026-03-02T04:14:00', 'Crime scene — 2026-CR-004', 'collected', NULL, 1);
INSERT INTO evidence_items (asset_tag, description, case_id, evidence_type_id, collected_date, crime_scene_location, current_status, disposal_date, collected_by)
VALUES ('TAG-004002', 'DNA swab — victim fingernail scrapings', 4, 2, '2026-03-02T06:37:00', 'Crime scene — 2026-CR-004', 'collected', NULL, 5);
INSERT INTO evidence_items (asset_tag, description, case_id, evidence_type_id, collected_date, crime_scene_location, current_status, disposal_date, collected_by)
VALUES ('TAG-004003', 'Blood spatter pattern — photographic evidence', 4, 2, '2026-03-01T19:51:00', 'Crime scene — 2026-CR-004', 'collected', NULL, 5);
INSERT INTO evidence_items (asset_tag, description, case_id, evidence_type_id, collected_date, crime_scene_location, current_status, disposal_date, collected_by)
VALUES ('TAG-004004', 'Clothing — victim shirt, torn and bloodstained', 4, 2, '2026-03-01T02:48:00', 'Crime scene — 2026-CR-004', 'collected', NULL, 1);
INSERT INTO evidence_items (asset_tag, description, case_id, evidence_type_id, collected_date, crime_scene_location, current_status, disposal_date, collected_by)
VALUES ('TAG-005001', 'Laptop — Dell XPS 15, password-protected', 5, 3, '2026-03-10T12:44:00', 'Crime scene — 2026-CR-005', 'collected', NULL, 4);
INSERT INTO evidence_items (asset_tag, description, case_id, evidence_type_id, collected_date, crime_scene_location, current_status, disposal_date, collected_by)
VALUES ('TAG-005002', 'External hard drive — 2TB Seagate', 5, 3, '2026-03-11T05:21:00', 'Crime scene — 2026-CR-005', 'collected', NULL, 4);
INSERT INTO evidence_items (asset_tag, description, case_id, evidence_type_id, collected_date, crime_scene_location, current_status, disposal_date, collected_by)
VALUES ('TAG-005003', 'Fake ID documents — 5x driver licenses', 5, 5, '2026-03-10T19:09:00', 'Crime scene — 2026-CR-005', 'collected', NULL, 4);
INSERT INTO evidence_items (asset_tag, description, case_id, evidence_type_id, collected_date, crime_scene_location, current_status, disposal_date, collected_by)
VALUES ('TAG-005004', 'Cellphone — Samsung Galaxy S25', 5, 3, '2026-03-10T15:48:00', 'Crime scene — 2026-CR-005', 'collected', NULL, 4);
INSERT INTO evidence_items (asset_tag, description, case_id, evidence_type_id, collected_date, crime_scene_location, current_status, disposal_date, collected_by)
VALUES ('TAG-006001', 'Service weapon — Glock 17, officer firearm', 6, 6, '2026-04-01T23:06:00', 'Crime scene — 2026-CR-006', 'collected', NULL, 5);
INSERT INTO evidence_items (asset_tag, description, case_id, evidence_type_id, collected_date, crime_scene_location, current_status, disposal_date, collected_by)
VALUES ('TAG-006002', 'Body camera footage — officer body cam', 6, 3, '2026-04-01T07:24:00', 'Crime scene — 2026-CR-006', 'collected', NULL, 5);
INSERT INTO evidence_items (asset_tag, description, case_id, evidence_type_id, collected_date, crime_scene_location, current_status, disposal_date, collected_by)
VALUES ('TAG-006003', 'Shell casings — 5x 9mm casings from scene', 6, 6, '2026-04-01T08:22:00', 'Crime scene — 2026-CR-006', 'collected', NULL, 5);
INSERT INTO evidence_items (asset_tag, description, case_id, evidence_type_id, collected_date, crime_scene_location, current_status, disposal_date, collected_by)
VALUES ('TAG-006004', 'DNA swab — suspect cheek swab', 6, 2, '2026-04-02T00:38:00', 'Crime scene — 2026-CR-006', 'collected', NULL, 5);
INSERT INTO evidence_items (asset_tag, description, case_id, evidence_type_id, collected_date, crime_scene_location, current_status, disposal_date, collected_by)
VALUES ('TAG-007001', 'Stolen merchandise — 3x designer handbags', 7, 7, '2026-05-01T18:51:00', 'Crime scene — 2026-CR-007', 'collected', NULL, 3);
INSERT INTO evidence_items (asset_tag, description, case_id, evidence_type_id, collected_date, crime_scene_location, current_status, disposal_date, collected_by)
VALUES ('TAG-008001', 'Crowbar — pry marks match door frame', 8, 1, '2026-05-10T04:46:00', 'Crime scene — 2026-CR-008', 'collected', NULL, 3);
INSERT INTO evidence_items (asset_tag, description, case_id, evidence_type_id, collected_date, crime_scene_location, current_status, disposal_date, collected_by)
VALUES ('TAG-008002', 'Footwear impression — mud cast from backyard', 8, 2, '2026-05-11T07:34:00', 'Crime scene — 2026-CR-008', 'collected', NULL, 3);

-- Custody Transfers (~50)
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (1, NULL, 1, '2026-01-20T19:15:00', 1, 'collection', 'Initial collection from crime scene');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (1, 1, 2, '2026-01-20T21:15:00', 1, 'transport', 'Transport to central evidence storage');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (1, 2, 4, '2026-01-20T22:15:00', 10, 'court_delivery', 'Delivered for court proceedings');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (1, 4, 3, '2026-01-23T22:15:00', 1, 'transport', 'Returned from court to evidence storage');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (1, 3, 15, '2026-01-24T22:15:00', 1, 'disposal', 'Evidence disposed — case closed');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (2, NULL, 1, '2026-01-20T16:08:00', 1, 'collection', 'Initial collection from crime scene');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (2, 1, 2, '2026-01-20T18:08:00', 1, 'transport', 'Transport to central evidence storage');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (2, 2, 6, '2026-01-20T19:08:00', 9, 'lab_submission', 'Submitted for forensic analysis');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (2, 6, 2, '2026-01-21T19:08:00', 1, 'lab_return', 'Returned from lab — analysis complete');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (2, 2, 13, '2026-01-22T19:08:00', 1, 'defense_viewing', 'Defense attorney evidence inspection');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (2, 13, 3, '2026-01-22T21:08:00', 1, 'transport', 'Returned after defense viewing');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (2, 3, 15, '2026-01-23T21:08:00', 1, 'disposal', 'Evidence disposed — case closed');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (3, NULL, 1, '2026-01-20T08:43:00', 1, 'collection', 'Initial collection from crime scene');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (3, 1, 3, '2026-01-20T10:43:00', 1, 'transport', 'Transport to central evidence storage');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (3, 3, 6, '2026-01-20T11:43:00', 9, 'lab_submission', 'Submitted for forensic analysis');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (3, 6, 1, '2026-01-26T11:43:00', 1, 'lab_return', 'Returned from lab — analysis complete');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (3, 1, 3, '2026-01-27T11:43:00', 10, 'court_delivery', 'Delivered for court proceedings');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (3, 3, 2, '2026-01-30T11:43:00', 1, 'transport', 'Returned from court to evidence storage');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (3, 2, 13, '2026-01-31T11:43:00', 1, 'defense_viewing', 'Defense attorney evidence inspection');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (3, 13, 3, '2026-01-31T13:43:00', 1, 'transport', 'Returned after defense viewing');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (3, 3, 15, '2026-02-01T13:43:00', 1, 'disposal', 'Evidence disposed — case closed');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (4, NULL, 4, '2026-01-21T12:05:00', 1, 'collection', 'Initial collection from crime scene');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (4, 4, 2, '2026-01-21T14:05:00', 1, 'transport', 'Transport to central evidence storage');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (4, 2, 15, '2026-01-21T15:05:00', 1, 'disposal', 'Evidence disposed — case closed');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (5, NULL, 2, '2026-02-02T15:27:00', 1, 'collection', 'Initial collection from crime scene');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (5, 2, 3, '2026-02-02T17:27:00', 1, 'transport', 'Transport to central evidence storage');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (5, 3, 15, '2026-02-02T18:27:00', 1, 'disposal', 'Evidence disposed — case closed');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (6, NULL, 2, '2026-02-01T04:01:00', 1, 'collection', 'Initial collection from crime scene');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (6, 2, 1, '2026-02-01T06:01:00', 1, 'transport', 'Transport to central evidence storage');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (6, 1, 8, '2026-02-01T07:01:00', 9, 'lab_submission', 'Submitted for forensic analysis');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (6, 8, 4, '2026-02-03T07:01:00', 1, 'lab_return', 'Returned from lab — analysis complete');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (6, 4, 5, '2026-02-04T07:01:00', 10, 'court_delivery', 'Delivered for court proceedings');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (6, 5, 3, '2026-02-05T07:01:00', 1, 'transport', 'Returned from court to evidence storage');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (6, 3, 14, '2026-02-06T07:01:00', 1, 'defense_viewing', 'Defense attorney evidence inspection');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (6, 14, 5, '2026-02-06T09:01:00', 1, 'transport', 'Returned after defense viewing');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (6, 5, 15, '2026-02-07T09:01:00', 1, 'disposal', 'Evidence disposed — case closed');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (7, NULL, 2, '2026-02-01T07:13:00', 1, 'collection', 'Initial collection from crime scene');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (7, 2, 4, '2026-02-01T09:13:00', 1, 'transport', 'Transport to central evidence storage');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (7, 4, 5, '2026-02-01T10:13:00', 10, 'court_delivery', 'Delivered for court proceedings');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (7, 5, 2, '2026-02-03T10:13:00', 1, 'transport', 'Returned from court to evidence storage');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (7, 2, 15, '2026-02-04T10:13:00', 1, 'disposal', 'Evidence disposed — case closed');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (8, NULL, 2, '2026-02-01T16:32:00', 1, 'collection', 'Initial collection from crime scene');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (8, 2, 3, '2026-02-01T18:32:00', 1, 'transport', 'Transport to central evidence storage');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (8, 3, 6, '2026-02-01T19:32:00', 8, 'lab_submission', 'Submitted for forensic analysis');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (8, 6, 1, '2026-02-08T19:32:00', 1, 'lab_return', 'Returned from lab — analysis complete');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (8, 1, 3, '2026-02-09T19:32:00', 10, 'court_delivery', 'Delivered for court proceedings');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (8, 3, 5, '2026-02-12T19:32:00', 1, 'transport', 'Returned from court to evidence storage');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (8, 5, 15, '2026-02-13T19:32:00', 1, 'disposal', 'Evidence disposed — case closed');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (9, NULL, 1, '2026-02-16T16:01:00', 1, 'collection', 'Initial collection from crime scene');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (9, 1, 5, '2026-02-16T18:01:00', 1, 'transport', 'Transport to central evidence storage');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (9, 5, 7, '2026-02-16T19:01:00', 9, 'lab_submission', 'Submitted for forensic analysis');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (9, 7, 1, '2026-02-21T19:01:00', 1, 'lab_return', 'Returned from lab — analysis complete');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (9, 1, 2, '2026-02-22T19:01:00', 10, 'court_delivery', 'Delivered for court proceedings');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (9, 2, 4, '2026-02-25T19:01:00', 1, 'transport', 'Returned from court to evidence storage');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (9, 4, 15, '2026-02-26T19:01:00', 1, 'disposal', 'Evidence disposed — case closed');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (10, NULL, 1, '2026-02-16T13:12:00', 1, 'collection', 'Initial collection from crime scene');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (10, 1, 4, '2026-02-16T15:12:00', 1, 'transport', 'Transport to central evidence storage');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (10, 4, 7, '2026-02-16T16:12:00', 8, 'lab_submission', 'Submitted for forensic analysis');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (10, 7, 1, '2026-02-20T16:12:00', 1, 'lab_return', 'Returned from lab — analysis complete');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (10, 1, 15, '2026-02-21T16:12:00', 1, 'disposal', 'Evidence disposed — case closed');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (11, NULL, 1, '2026-02-16T23:41:00', 1, 'collection', 'Initial collection from crime scene');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (11, 1, 4, '2026-02-17T01:41:00', 1, 'transport', 'Transport to central evidence storage');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (11, 4, 15, '2026-02-17T02:41:00', 1, 'disposal', 'Evidence disposed — case closed');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (12, NULL, 4, '2026-02-16T22:34:00', 1, 'collection', 'Initial collection from crime scene');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (12, 4, 1, '2026-02-17T00:34:00', 1, 'transport', 'Transport to central evidence storage');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (12, 1, 3, '2026-02-17T01:34:00', 10, 'court_delivery', 'Delivered for court proceedings');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (12, 3, 4, '2026-02-18T01:34:00', 1, 'transport', 'Returned from court to evidence storage');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (12, 4, 15, '2026-02-19T01:34:00', 1, 'disposal', 'Evidence disposed — case closed');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (13, NULL, 1, '2026-03-02T04:14:00', 1, 'collection', 'Initial collection from crime scene');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (13, 1, 2, '2026-03-02T06:14:00', 1, 'transport', 'Transport to central evidence storage');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (13, 2, 7, '2026-03-02T07:14:00', 8, 'lab_submission', 'Submitted for forensic analysis');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (13, 7, 3, '2026-03-03T07:14:00', 1, 'lab_return', 'Returned from lab — analysis complete');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (14, NULL, 5, '2026-03-02T06:37:00', 1, 'collection', 'Initial collection from crime scene');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (14, 5, 3, '2026-03-02T08:37:00', 1, 'transport', 'Transport to central evidence storage');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (14, 3, 6, '2026-03-02T09:37:00', 8, 'lab_submission', 'Submitted for forensic analysis');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (14, 6, 4, '2026-03-03T09:37:00', 1, 'lab_return', 'Returned from lab — analysis complete');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (15, NULL, 5, '2026-03-01T19:51:00', 1, 'collection', 'Initial collection from crime scene');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (15, 5, 2, '2026-03-01T21:51:00', 1, 'transport', 'Transport to central evidence storage');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (15, 2, 7, '2026-03-01T22:51:00', 8, 'lab_submission', 'Submitted for forensic analysis');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (15, 7, 5, '2026-03-04T22:51:00', 1, 'lab_return', 'Returned from lab — analysis complete');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (16, NULL, 1, '2026-03-01T02:48:00', 1, 'collection', 'Initial collection from crime scene');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (16, 1, 3, '2026-03-01T04:48:00', 1, 'transport', 'Transport to central evidence storage');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (17, NULL, 4, '2026-03-10T12:44:00', 1, 'collection', 'Initial collection from crime scene');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (17, 4, 3, '2026-03-10T14:44:00', 1, 'transport', 'Transport to central evidence storage');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (17, 3, 8, '2026-03-10T15:44:00', 9, 'lab_submission', 'Submitted for forensic analysis');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (17, 8, 5, '2026-03-14T15:44:00', 1, 'lab_return', 'Returned from lab — analysis complete');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (17, 5, 2, '2026-03-15T15:44:00', 10, 'court_delivery', 'Delivered for court proceedings');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (17, 2, 1, '2026-03-16T15:44:00', 1, 'transport', 'Returned from court to evidence storage');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (17, 1, 14, '2026-03-17T15:44:00', 1, 'defense_viewing', 'Defense attorney evidence inspection');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (17, 14, 5, '2026-03-17T17:44:00', 1, 'transport', 'Returned after defense viewing');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (18, NULL, 4, '2026-03-11T05:21:00', 1, 'collection', 'Initial collection from crime scene');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (18, 4, 2, '2026-03-11T07:21:00', 1, 'transport', 'Transport to central evidence storage');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (18, 2, 6, '2026-03-11T08:21:00', 8, 'lab_submission', 'Submitted for forensic analysis');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (18, 6, 1, '2026-03-17T08:21:00', 1, 'lab_return', 'Returned from lab — analysis complete');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (18, 1, 2, '2026-03-18T08:21:00', 10, 'court_delivery', 'Delivered for court proceedings');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (18, 2, 1, '2026-03-20T08:21:00', 1, 'transport', 'Returned from court to evidence storage');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (19, NULL, 4, '2026-03-10T19:09:00', 1, 'collection', 'Initial collection from crime scene');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (19, 4, 3, '2026-03-10T21:09:00', 1, 'transport', 'Transport to central evidence storage');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (19, 3, 2, '2026-03-10T22:09:00', 10, 'court_delivery', 'Delivered for court proceedings');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (19, 2, 5, '2026-03-13T22:09:00', 1, 'transport', 'Returned from court to evidence storage');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (19, 5, 13, '2026-03-14T22:09:00', 1, 'defense_viewing', 'Defense attorney evidence inspection');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (19, 13, 4, '2026-03-15T00:09:00', 1, 'transport', 'Returned after defense viewing');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (20, NULL, 4, '2026-03-10T15:48:00', 1, 'collection', 'Initial collection from crime scene');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (20, 4, 2, '2026-03-10T17:48:00', 1, 'transport', 'Transport to central evidence storage');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (20, 2, 8, '2026-03-10T18:48:00', 9, 'lab_submission', 'Submitted for forensic analysis');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (20, 8, 4, '2026-03-13T18:48:00', 1, 'lab_return', 'Returned from lab — analysis complete');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (20, 4, 1, '2026-03-14T18:48:00', 10, 'court_delivery', 'Delivered for court proceedings');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (20, 1, 2, '2026-03-17T18:48:00', 1, 'transport', 'Returned from court to evidence storage');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (20, 2, 14, '2026-03-18T18:48:00', 1, 'defense_viewing', 'Defense attorney evidence inspection');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (20, 14, 3, '2026-03-18T20:48:00', 1, 'transport', 'Returned after defense viewing');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (21, NULL, 5, '2026-04-01T23:06:00', 1, 'collection', 'Initial collection from crime scene');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (21, 5, 1, '2026-04-02T01:06:00', 1, 'transport', 'Transport to central evidence storage');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (21, 1, 6, '2026-04-02T02:06:00', 9, 'lab_submission', 'Submitted for forensic analysis');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (21, 6, 4, '2026-04-04T02:06:00', 1, 'lab_return', 'Returned from lab — analysis complete');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (21, 4, 5, '2026-04-05T02:06:00', 10, 'court_delivery', 'Delivered for court proceedings');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (21, 5, 1, '2026-04-06T02:06:00', 1, 'transport', 'Returned from court to evidence storage');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (22, NULL, 5, '2026-04-01T07:24:00', 1, 'collection', 'Initial collection from crime scene');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (22, 5, 1, '2026-04-01T09:24:00', 1, 'transport', 'Transport to central evidence storage');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (22, 1, 8, '2026-04-01T10:24:00', 8, 'lab_submission', 'Submitted for forensic analysis');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (22, 8, 2, '2026-04-02T10:24:00', 1, 'lab_return', 'Returned from lab — analysis complete');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (22, 2, 5, '2026-04-03T10:24:00', 10, 'court_delivery', 'Delivered for court proceedings');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (22, 5, 2, '2026-04-05T10:24:00', 1, 'transport', 'Returned from court to evidence storage');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (23, NULL, 5, '2026-04-01T08:22:00', 1, 'collection', 'Initial collection from crime scene');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (23, 5, 1, '2026-04-01T10:22:00', 1, 'transport', 'Transport to central evidence storage');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (23, 1, 6, '2026-04-01T11:22:00', 9, 'lab_submission', 'Submitted for forensic analysis');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (23, 6, 4, '2026-04-04T11:22:00', 1, 'lab_return', 'Returned from lab — analysis complete');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (23, 4, 5, '2026-04-05T11:22:00', 10, 'court_delivery', 'Delivered for court proceedings');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (23, 5, 2, '2026-04-06T11:22:00', 1, 'transport', 'Returned from court to evidence storage');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (23, 2, 12, '2026-04-07T11:22:00', 1, 'defense_viewing', 'Defense attorney evidence inspection');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (23, 12, 5, '2026-04-07T13:22:00', 1, 'transport', 'Returned after defense viewing');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (24, NULL, 5, '2026-04-02T00:38:00', 1, 'collection', 'Initial collection from crime scene');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (24, 5, 1, '2026-04-02T02:38:00', 1, 'transport', 'Transport to central evidence storage');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (24, 1, 5, '2026-04-02T03:38:00', 10, 'court_delivery', 'Delivered for court proceedings');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (24, 5, 2, '2026-04-05T03:38:00', 1, 'transport', 'Returned from court to evidence storage');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (24, 2, 14, '2026-04-06T03:38:00', 1, 'defense_viewing', 'Defense attorney evidence inspection');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (24, 14, 1, '2026-04-06T05:38:00', 1, 'transport', 'Returned after defense viewing');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (25, NULL, 3, '2026-05-01T18:51:00', 1, 'collection', 'Initial collection from crime scene');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (25, 3, 2, '2026-05-01T20:51:00', 1, 'transport', 'Transport to central evidence storage');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (25, 2, 6, '2026-05-01T21:51:00', 8, 'lab_submission', 'Submitted for forensic analysis');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (25, 6, 1, '2026-05-05T21:51:00', 1, 'lab_return', 'Returned from lab — analysis complete');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (26, NULL, 3, '2026-05-10T04:46:00', 1, 'collection', 'Initial collection from crime scene');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (26, 3, 2, '2026-05-10T06:46:00', 1, 'transport', 'Transport to central evidence storage');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (26, 2, 6, '2026-05-10T07:46:00', 8, 'lab_submission', 'Submitted for forensic analysis');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (26, 6, 5, '2026-05-14T07:46:00', 1, 'lab_return', 'Returned from lab — analysis complete');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (27, NULL, 3, '2026-05-11T07:34:00', 1, 'collection', 'Initial collection from crime scene');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (27, 3, 4, '2026-05-11T09:34:00', 1, 'transport', 'Transport to central evidence storage');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (27, 4, 14, '2026-05-11T10:34:00', 1, 'defense_viewing', 'Defense attorney evidence inspection');
INSERT INTO custody_transfers (evidence_item_id, from_personnel_id, to_personnel_id, transfer_timestamp, storage_location_id, transfer_type, notes)
VALUES (27, 14, 3, '2026-05-11T12:34:00', 1, 'transport', 'Returned after defense viewing');

-- Lab Tests (12)
INSERT INTO lab_tests (evidence_item_id, test_type, requested_by, lab_technician, status, results_summary, request_date, completion_date)
VALUES (1, 'ballistics', 1, 6, 'completed', 'Ballistics match — weapon linked to crime scene', '2026-01-20', '2026-02-01');
INSERT INTO lab_tests (evidence_item_id, test_type, requested_by, lab_technician, status, results_summary, request_date, completion_date)
VALUES (2, 'dna', 1, 6, 'completed', 'Digital evidence extracted — relevant files recovered', '2026-01-20', '2026-02-06');
INSERT INTO lab_tests (evidence_item_id, test_type, requested_by, lab_technician, status, results_summary, request_date, completion_date)
VALUES (5, 'fingerprint', 2, 8, 'completed', 'Fingerprint match — positive identification', '2026-02-02', '2026-02-13');
INSERT INTO lab_tests (evidence_item_id, test_type, requested_by, lab_technician, status, results_summary, request_date, completion_date)
VALUES (9, 'fingerprint', 1, 7, 'completed', 'Toxicology positive — controlled substances detected', '2026-02-16', '2026-03-08');
INSERT INTO lab_tests (evidence_item_id, test_type, requested_by, lab_technician, status, results_summary, request_date, completion_date)
VALUES (13, 'digital_forensics', 1, 7, 'requested', NULL, '2026-03-02', NULL);
INSERT INTO lab_tests (evidence_item_id, test_type, requested_by, lab_technician, status, results_summary, request_date, completion_date)
VALUES (15, 'dna', 5, 6, 'requested', NULL, '2026-03-01', NULL);
INSERT INTO lab_tests (evidence_item_id, test_type, requested_by, lab_technician, status, results_summary, request_date, completion_date)
VALUES (16, 'digital_forensics', 1, 6, 'in_progress', 'Preliminary analysis underway', '2026-03-01', NULL);
INSERT INTO lab_tests (evidence_item_id, test_type, requested_by, lab_technician, status, results_summary, request_date, completion_date)
VALUES (17, 'toxicology', 4, 8, 'in_progress', 'Preliminary analysis underway', '2026-03-10', NULL);
INSERT INTO lab_tests (evidence_item_id, test_type, requested_by, lab_technician, status, results_summary, request_date, completion_date)
VALUES (18, 'dna', 4, 6, 'in_progress', 'Preliminary analysis underway', '2026-03-11', NULL);
INSERT INTO lab_tests (evidence_item_id, test_type, requested_by, lab_technician, status, results_summary, request_date, completion_date)
VALUES (20, 'toxicology', 4, 6, 'in_progress', 'Preliminary analysis underway', '2026-03-10', NULL);
INSERT INTO lab_tests (evidence_item_id, test_type, requested_by, lab_technician, status, results_summary, request_date, completion_date)
VALUES (21, 'ballistics', 5, 8, 'in_progress', 'Preliminary analysis underway', '2026-04-01', NULL);
INSERT INTO lab_tests (evidence_item_id, test_type, requested_by, lab_technician, status, results_summary, request_date, completion_date)
VALUES (23, 'fingerprint', 5, 8, 'requested', NULL, '2026-04-01', NULL);

-- Evidence Requests (8)
INSERT INTO evidence_requests (evidence_item_id, requesting_attorney_id, status, request_date, decision_date, approved_by_id, denial_reason)
VALUES (3, 12, 'approved', '2026-01-20', '2026-01-26', 9, NULL);
INSERT INTO evidence_requests (evidence_item_id, requesting_attorney_id, status, request_date, decision_date, approved_by_id, denial_reason)
VALUES (4, 12, 'pending', '2026-01-21', NULL, 9, NULL);
INSERT INTO evidence_requests (evidence_item_id, requesting_attorney_id, status, request_date, decision_date, approved_by_id, denial_reason)
VALUES (6, 13, 'approved', '2026-02-01', '2026-02-27', 10, NULL);
INSERT INTO evidence_requests (evidence_item_id, requesting_attorney_id, status, request_date, decision_date, approved_by_id, denial_reason)
VALUES (7, 13, 'denied', '2026-02-01', '2026-02-25', 10, 'Insufficient relevance to case — evidence not material to defense');
INSERT INTO evidence_requests (evidence_item_id, requesting_attorney_id, status, request_date, decision_date, approved_by_id, denial_reason)
VALUES (10, 14, 'approved', '2026-02-16', '2026-03-18', 9, NULL);
INSERT INTO evidence_requests (evidence_item_id, requesting_attorney_id, status, request_date, decision_date, approved_by_id, denial_reason)
VALUES (13, 12, 'fulfilled', '2026-03-02', '2026-04-01', 9, NULL);
INSERT INTO disclosure_logs (evidence_item_id, evidence_request_id, viewing_attorney_id, supervising_officer_id, view_date, view_type)
VALUES (13, 6, 12, 2, '2026-03-20T14:14:00', 'certified_copy');
INSERT INTO evidence_requests (evidence_item_id, requesting_attorney_id, status, request_date, decision_date, approved_by_id, denial_reason)
VALUES (15, 12, 'pending', '2026-03-01', NULL, 9, NULL);
INSERT INTO evidence_requests (evidence_item_id, requesting_attorney_id, status, request_date, decision_date, approved_by_id, denial_reason)
VALUES (17, 14, 'denied', '2026-03-10', '2026-03-26', 11, 'Insufficient relevance to case — evidence not material to defense');

COMMIT;

-- ============================================================================
-- Verification: Row counts
-- ============================================================================
SELECT 'courts' AS tbl, COUNT(*)::text AS cnt FROM courts
UNION ALL SELECT 'storage_locations', COUNT(*)::text FROM storage_locations
UNION ALL SELECT 'personnel', COUNT(*)::text FROM personnel
UNION ALL SELECT 'cases', COUNT(*)::text FROM cases
UNION ALL SELECT 'evidence_items', COUNT(*)::text FROM evidence_items
UNION ALL SELECT 'custody_transfers', COUNT(*)::text FROM custody_transfers
UNION ALL SELECT 'lab_tests', COUNT(*)::text FROM lab_tests
UNION ALL SELECT 'evidence_requests', COUNT(*)::text FROM evidence_requests
UNION ALL SELECT 'disclosure_logs', COUNT(*)::text FROM disclosure_logs
UNION ALL SELECT 'ai_summaries', COUNT(*)::text FROM ai_summaries
ORDER BY tbl;